# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  default:
    cmds:
      - task --list-all
    silent: true

  build:
    desc: Build App and install to /Applications
    cmds:
      - npm install && npm run tauri build -- --bundles app
      - cp -r "src-tauri/target/release/bundle/macos/TinyDataWarehouse.app" /Applications/

  release:
    desc: Upload built app to GitHub Release (re-release)
    cmds:
      - ./scripts/release.sh {{.CLI_ARGS}}

  mcp_log:
    cmds:
      - tail -f  ~/.tdwh/logs/mcp_access.log

  clean:
    desc: Clean
    cmds:
      - rm -rf src-tauri/target/
      - rm -rf dist/
      - rm -rf node_modules/
